;; -*- mode:scheme; coding:utf-8; -*-
;; Generated by genbind
;; /usr/local/bin/genbind -DSQL_API_FN -DFAR -t HWND=void* -tSQL_BIGUINT_TYPE -t_SQLOLDCHAR /cygdrive/c/Program Files (x86)/IBM/SQLLIB/include/sqlcli1.h -o (db2 cli) -s db2cli.txt -Osrc
(library (db2 cli)
    (export
      :all
     )
    (import
      (db2 cli constants)
      (db2 cli types)
      (db2 cli apis)
     )
)
